apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- Namespace_cert-manager-operator.yaml
- OperatorGroup_cert-manager-operator.yaml
- Subscription_cert-manager-subscription.yaml
