apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - KafkaTopic_gateway.message.external-message.yaml
  - KafkaTopic_cash.payment.created.yaml
  - KafkaTopic_account.balance.impact-apply.yaml
  - KafkaTopic_account.balance.impact-applied.yaml
  - KafkaTopic_gateway.message.generate-confirmation.yaml
  - KafkaTopic_gateway.message.write-to-dlq.yaml
  - KafkaTopic_dashboard.init.executor.yaml
