apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movies-app
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: movies-app
    server: https://kubernetes.default.svc
  project: movies-app
  source:
    path: app-config/kafka-client
    repoURL: https://github.com/ryan-highley/rh-streams-keycloak-certmgr-gitops
    kustomize:
      patches:
        - target:
            kind: Certificate
            name: kafka-client-cert-issuer
          patch: |-
            - op: replace
              path: /spec/commonName
              value: movies-app-kafka-client-ca
        - target:
            kind: Certificate
            name: kafka-client-cert
          patch: |-
            - op: replace
              path: /spec/commonName
              value: movies-app-kafka-client
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
