apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: music-app-kafka
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: music-app-kafka
    server: https://kubernetes.default.svc
  project: music-app
  source:
    path: app-config/streams-kafka/helm
    repoURL: https://github.com/ryan-highley/rh-streams-keycloak-certmgr-gitops
    helm:
      namespace: music-app-kafka
      releaseName: music-app
      valueFiles:
        - ../values-music-app.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
