apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movies-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: movies-app
    server: https://kubernetes.default.svc
  project: movies-app
  source:
    path: argocd/app-config/profiles/multi-cluster-kafka/movies-app/client-app
    repoURL: https://github.com/ryan-highley/rh-streams-keycloak-certmgr-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
