apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: broker
spec:
  kafka:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: PLACEHOLDER
          key: kafka-metrics-config.yaml
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
