apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-console
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kafka-console
    server: https://kubernetes.default.svc
  project: kafka-console
  source:
    path: app-config/kafka-console
    repoURL: https://github.com/ryan-highley/rh-streams-keycloak-certmgr-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
