apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movies-app-kafka
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: movies-app-kafka
    server: https://kubernetes.default.svc
  project: movies-app
  source:
    path: app-config/streams-kafka
    repoURL: https://github.com/ryan-highley/rh-streams-keycloak-certmgr-gitops
    helm:
      namespace: movies-app-kafka
      releaseName: movies-app
      valuesFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
