apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-client
spec:
  selector:
    matchLabels:
      app: kafka-client
  template:
    metadata:
      labels:
        app: kafka-client
    spec:
      containers:
        - name: client
          image: quay.io/strimzi/kafka:latest-kafka-4.0.0
          resources:
            requests:
              cpu: 125m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          command:
            - /bin/sh
            - -c
          args:
            - sleep infinity
