apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-client
spec:
  selector:
    matchLabels:
      app: kafka-client
  template:
    metadata:
      labels:
        app: kafka-client
    spec:
      containers:
        - name: client
          image: quay.io/strimzi/kafka:latest-kafka-4.0.0
          resources:
            requests:
              cpu: 125m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          command:
            - /bin/sh
            - -c
          args:
            - sleep infinity
          env:
            - name: STOREPASS
              valueFrom:
                secretKeyRef:
                  name: kafka-client-cert-secret-keystore
                  key: password
          volumeMounts:
            - name: kafka-client-cert
              readOnly: true
              mountPath: /opt/kafka/client/cert
            - name: kafka-client-config
              readOnly: true
              mountPath: /opt/kafka/client/config
      volumes:
        - name: kafka-client-cert
          secret:
            secretName: kafka-client-cert-secret
            defaultMode: 420
        - name: kafka-client-config
          configMap:
            name: kafka-client-config
            defaultMode: 420
