resources:
  # - Certificate_cert-issuer.yaml
  # - Issuer_cert-issuer.yaml
  # - Certificate_kafka-client-cert.yaml
  - Deployment_kafka-client.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  # - name: kafka-client-cert-secret-keystore
  #   behavior: create
  #   type: Opaque
  #   literals:
  #     - password=not-terribly-secure
  - name: kafka-client-config
    files:
      - kafka-client-config.properties
