cluster:
  name: music-app-broker
  authorization:
    type: simple
    superUsers:
      - CN=kafka-cli
      - kafka-console
  listeners:
    - name: tls
      port: 9093
      type: internal
      tls: true
      authentication:
        type: tls
    - name: console
      port: 9094
      type: internal
      tls: true
      authentication:
        type: scram-sha-512

topics:
  - name: albums
    spec:
      replicas: 3
      partitions: 12
  - name: artists
    spec:
      replicas: 3
      partitions: 24
  - name: bands
    spec:
      replicas: 3
      partitions: 12
  - name: producers
    spec:
      replicas: 3
      partitions: 24
  - name: songs
    spec:
      replicas: 3
      partitions: 48

clientApp:
  namespace: music-app
