apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: kafka-client-config
    behavior: replace
    files:
      - kafka-client-config.properties
