apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - Deployment_kafka-client.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: kafka-client-config
    files:
      - kafka-client-config.properties
