apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../../components/operators/openshift-cert-manager
  - ../../components/operators/rh-keycloak
  - ../../components/operators/amq-streams
  - ../../components/operators/streams-console
