apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/broker

components:
  # - ../../components/keycloak-oidc
  - ../../components/tls-authentication
  - ../../components/separate-node-pools
  - ../../components/prometheus
  - ../../components/kafka-console
  - ../../components/kafka-cli
  - ../../components/kafka-issuer
  - ../../components/boca-topics

transformers:
  - ../../base/transformers
  - ../../components/prometheus/transformers
  - ../../components/kafka-issuer/transformers
