apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-console-dex
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kafka-console-dex
    server: https://kubernetes.default.svc
  project: kafka-console
  source:
    path: app-config/kafka-console-dex
    repoURL: https://github.com/ryan-highley/rh-streams-keycloak-certmgr-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: '*'
      kind: Secret
      name: console-dex-token
      namespace: kafka-console-dex
      jsonPointers:
        - /data
