namespace: openshift-gitops

resources:
  - ../../base
  - movies-app/
  - music-app/

patches:
  - target:
      kind: Application
      name: app-config
    patch: |-
      - op: replace
        path: /spec/source/path
        value: argocd/app-config/profiles/multi-cluster-kafka-keycloak
