apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: music-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: music-app
    server: https://kubernetes.default.svc
  project: music-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
